Delimited serialization & range review
UAVCAN/public_regulated_data_types pull request #80
Opened 2020-08-25 20:50 UTC by pavel-kirienko

Addresses https://github.com/UAVCAN/specification/issues/90 and https://github.com/UAVCAN/specification/issues/94; depends on https://github.com/UAVCAN/pydsdl/pull/45

2020-08-27 23:31 UTC, thirtytwobits commented on README.md
> +0       | 6143      | Unregulated identifiers
Please submit a change to the specification first.

2020-10-11 19:43 UTC, thirtytwobits commented
We should provide @extent for all types that are not sealed. This will ensure the sizes of the core types can be read right from the DSDL without having to consult the specification and do the math to add in the default reserved memory.

2020-10-11 20:02 UTC, thirtytwobits requested changes

2020-10-12 18:15 UTC, pavel-kirienko commented on uavcan/node/7509.Heartbeat.1.0.uavcan
> +@extent 63 * 8            # Reserve space up to the largest single-frame CAN FD transfer.
> What if we went with 15 bytes which still allows for a larger heartbeat in the future that would take two CAN 2.0 frames to transmit.

Updated, but note that a two-frame Classic CAN transfer can carry (7 bytes of payload per frame) * (2 frames) - (2 bytes of CRC) = 12 bytes.

2020-10-12 18:22 UTC, thirtytwobits approved these changes

2020-10-12 18:26 UTC, merged